language: php

sudo: required
dist: trusty
group: edge

cache:
  directories:
    - $HOME/.composer

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm-3.12
  - hhvm-nightly

env:
  # to properly install phpX-pgsql
  - DB=pgsql
  - DB=hhvm-pgsql

addons:
  postgresql: '9.4'

matrix:
  exclude:
    # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
    - php: hhvm-3.9
      env: DB=pgsql
    - php: hhvm-3.12
      env: DB=pgsql
    - php: hhvm-nightly
      env: DB=pgsql
    # Skip hhvm-pgsql installation in normal php
    - php: '5.5'
      env: DB=hhvm-pgsql
    - php: '5.6'
      env: DB=hhvm-pgsql
    - php: '7.0'
      env: DB=hhvm-pgsql
    - php: 'nightly'
      env: DB=hhvm-pgsql

before_install:
  - composer self-update --stable
  - export DB_CONNECTION=pgsql
  - export DB_HOST=127.0.0.1
  - export DB_DATABASE=travis
  - export DB_USERNAME=travis
  - export DB_PASSWORD=""
  - export DB_SCHEMA=public
  - psql -U "$DB_USERNAME" --host="$DB_HOST" "$DB_DATABASE" -c 'CREATE EXTENSION "uuid-ossp";'
  - sh -c "if [ '$DB' = 'hhvm-pgsql' ]; then ./.travis/install_hhvm_pgsql.sh; fi"
  - sh -c "if [ '$DB' != 'hhvm-pgsql' ]; then ./.travis/install_php_apc.sh; fi"
  - sh -c "if [ '$DB' != 'hhvm-pgsql' ] &&  [ '$(php -r 'echo extension_loaded("xdebug");')' != '1' ]; then echo 'xdebug not loaded'; exit 1; fi"

install:
  - composer install --prefer-dist -vvv -o
  - cp -pdf .env.example .env
  - php artisan key:generate
  - php artisan migrate --pretend

script:
  - php artisan migrate
  - php artisan config:cache
  - php artisan route:cache
  - ./vendor/bin/phpunit -v
  - php artisan migrate:rollback
